name: Deploy SAM Lambda Function

on:
  push:
    branches: 
      - master

env:
  S3_BUCKET_NAME: pgr301-couch-explorers
  STACK_NAME: couch-explorers-stack 
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
          contents: read

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

    - name: Validate SAM Template
      run: sam validate --template /home/ec2-user/environment/sam-lambda/template.yaml
      
    - name: Build SAM Application
      run: sam build

    - name: Deploy SAM Application
      run: |
          sam deploy --stack-name $STACK_NAME --s3-bucket $S3_BUCKET_NAME --capabilities CAPABILITY_IAM --region ${{ secrets.AWS_REGION }} --no-confirm-changeset

    - name: Output API Gateway Endpoint
      run: |
          aws cloudformation describe-stacks --stack-name $STACK_NAME --query "Stacks[0].Outputs" --output table
