name: Deploy SAM Lambda Function

on:
  push:
    branches: 
      - master

env:
  S3_BUCKET_NAME: pgr301-couch-explorers
  STACK_NAME: couch-explorers-stack 
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
          contents: read

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Python 3.8
      run: |
        sudo apt-get update -y
        sudo apt-get install -y python3.8 python3.8-dev python3.8-venv
        sudo ln -s /usr/bin/python3.8 /usr/bin/python  # Ensure 'python' points to python3.8
        python --version  # Verify Python version
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
    - name: Build SAM Application
      run: sam build --template /home/runner/work/-sam-lambda/-sam-lambda/sam-lambda/template.yaml

    - name: Deploy SAM Application 
      run: |
          sam deploy --template /home/runner/work/-sam-lambda/-sam-lambda/sam-lambda/template.yaml --stack-name $STACK_NAME --s3-bucket $S3_BUCKET_NAME --capabilities CAPABILITY_IAM --region ${{ secrets.AWS_REGION }} --no-confirm-changeset

    - name: Output API Gateway Endpoint
      run: |
          aws cloudformation describe-stacks --stack-name $STACK_NAME --query "Stacks[0].Outputs" --output table
